var editgrid = {};
editgrid.config = {
    "isRemoteGrid":1,
    "oooc_url":1,
    "gridletHost":"localhost",
    "staticUrl":"editgrid/static/",
    "eventdDomainSuffix":-1,
    "defaultFont":"Arial",
    "docFunctionBase":"editgrid/doc/function/",
    "transportFactory":"std.ajax.getScriptTagTransport",
    "hideMenuItems":[],
    "initialSessionId":"4cdb1a728c0fbbafba51a68bc91b10af202d9f04",
    "enableRemoteData":1,
    "enableVerticalAlign":0,
    "gridletBaseUrl":"/editgrid/",
    "revUrl":"/editgrid/",
    "gridletDebug":0,
    "gridletEnabled":0,
    "timingSheetDiff":15000,
    "gridEventdUrl":"/editgrid/",
    "profileUrl":"/editgrid/js/",
    "jsonPath":"cmd/json/",
    "SidePaneChat":0,
    "baseUrl":"/editgrid/",
    "eventdClientFactory":"eventd.createCrossDomainClient",
    "timingKeepAlive":240000,
    "acceptFonts":{
        "Garamond":"Garamond",
        "Geneva":"Geneva",
        "Century Gothic":"Century Gothic",
        "Arial":"Arial",
        "Times New Roman":"Times New Roman",
        "Tahoma":"Tahoma",
        "Georgia":"Georgia",
        "Trebuchet MS":"Trebuchet MS",
        "Comic Sans MS":"Comic Sans MS",
        "Verdana":"Verdana",
        "Courier New":"Courier New"
    }
};
