var _locale = {
	" Column: [_1]" : "列: &1",
	" Columns: [_1] to [_2]" : "列: &1 到 &2",
	" Row: [_1]" : "行: &1",
	" Row: [_1] to [_2]" : "行: &1 到 &2",
	"&1 has entered. (&2)" : "&1 已进入。 (&2)",
	"&1 has left. (&2)" : "&1 已离开。 (&2)",
	"&1 has left. (timeout, &2)" : "&1 已离开。 (没有响应, &2)",
	"&1 users chatting, " : "&1 users chatting, ",
	"&1 users, &2 new msgs" : "&1 名用户, &2 条新信息。",
	"(none)" : "(无)",
	"-- Please Select --" : "-- 请选择 --",
	"403 - Forbidden" : "403 - Forbidden",
	"404 - Not found" : "404 - Not found",
	"500 - Internal server error" : "500 - Internal server error",
	"A new version of EditGrid is available." : "A new version of EditGrid is available.",
	"A server error has occurred. Your lastest changes, if any, may be lost." : "A server error has occurred. Your lastest changes, if any, may be lost.",
	"AND implements the logical AND function: the result is TRUE if all of the expressions evaluate to TRUE, otherwise it returns FALSE." : "如果所有元素的值为真，结果为真。 反之为假。",
	"AVERAGE computes the average of all the values and cells referenced in the argument list.  This is equivalent to the sum of the arguments divided by the count of the arguments." : "AVERAGE 返回引数的平均值，即相等于所有数值总和除以数值项目。",
	"About RTU" : "About RTU",
	"Adjacent horizontal bars grouped by major and minor categories." : "用条形图比较相邻的单元格。",
	"Adjacent vertical bars grouped by major and minor categories." : "用柱形图比较相邻的单元格。",
	"Advanced" : "Advanced",
	"Advanced..." : "高级 ...",
	"Alexa" : "Alexa",
	"Align Center, Ctrl+E" : "居中 Ctrl+E",
	"Align Left, Ctrl+L" : "靠左对齐 Ctrl+L",
	"Align Right" : "Align Right",
	"Align Right, Ctrl+R" : "靠右对齐 Ctrl+R",
	"All data will be lost." : "All data will be lost.",
	"Angle" : "Angle",
	"Anonymous User" : "匿名用户",
	"Application error" : "Application error",
	"Application name" : "Application name",
	"Apply Cell/Range Lock" : "应用 单元格/范围 锁",
	"Are you sure you want to delete the selected redirection?" : "Are you sure you want to delete the selected redirection?",
	"Are you sure you want to delete the sheet '[_1]'?" : "Are you sure you want to delete the sheet '&1'?",
	"Are you sure you want to delete this object?" : "您是否确定删除此对象?",
	"Are you sure you want to purge [_1] selected spreadsheets?" : "Are you sure you want to purge &1 selected spreadsheets?",
	"Are you sure you want to purge the selected spreadsheet?" : "Are you sure you want to purge the selected spreadsheet?",
	"Are you sure you want to restore [_1] selected spreadsheets?" : "Are you sure you want to restore &1 selected spreadsheets?",
	"Are you sure you want to restore the selected spreadsheet?" : "Are you sure you want to restore the selected spreadsheet?",
	"Are you sure you want to unlock this cell/range?" : "您确定解除此 单元格/范围 的锁定吗？",
	"Area" : "面积图",
	"Area Plot" : "面积图 (一般)",
	"Attribution" : "Attribution",
	"Attribution No Derivatives" : "Attribution No Derivatives",
	"Attribution Non-commercial" : "Attribution Non-commercial",
	"Attribution Non-commercial No Derivatives" : "Attribution Non-commercial No Derivatives",
	"Attribution Non-commercial Share Alike" : "Attribution Non-commercial Share Alike",
	"Attribution Share Alike" : "Attribution Share Alike",
	"Auto Fit Selection" : "自动调整列宽及行高",
	"Autofill" : "Autofill",
	"Autofill Down" : "Autofill Down",
	"Autofill Right" : "Autofill Right",
	"Automatic" : "自动",
	"Back to My Workspace" : "返回我的工作坊",
	"Background Color" : "背景颜色",
	"Bar / Column" : "条形 / 柱形图",
	"Bar Plot" : "条形图",
	"Body" : "Body",
	"Bold, Ctrl+B" : "粗体 Ctrl+B",
	"Borders" : "边框",
	"Box-Plot" : "箱形图",
	"Bubble" : "气泡图",
	"Bubble Plot" : "气泡图",
	"CONCATENATE returns the string obtained by concatenation of the given strings." : "CONCATENATE 将数个字符串合併为一个字符串。",
	"CONTINUE reterieve value from ranged data" : "CONTINUE reterieve value from ranged data",
	"COUNTIF function counts the number of cells in the given range that meet the given criteria." : "COUNTIF 返回某一单元格范围中符合指定条件的单元格数目。",
	"Calculator" : "Calculator",
	"Cancel" : "取消",
	"Cannot delete this sheet:" : "Cannot delete this sheet:",
	"Cannot find cell with value '[_1]'" : "找不到包含 '&1' 的单元格",
	"Cannot start JStalyst application properly!" : "Cannot start JStalyst application properly!",
	"Cannot update link sheet on an old revision." : "Cannot update link sheet on an old revision.",
	"Cell Comment" : "Cell Comment",
	"Cell Properties" : "单元格属性",
	"Cell Widget" : "Cell Widget",
	"Cell/Range Lock" : "Cell/Range Lock",
	"Cell/Range Locked" : "单元格/范围 已锁定",
	"Cell/Region" : "Cell/Region",
	"Chart" : "图表",
	"Chat" : "聊天",
	"Chat room is full" : "Chat room is full",
	"Chat session not started" : "聊天会议功能未启动",
	"Checkbox" : "Checkbox",
	"Clear" : "Clear",
	"Clear All" : "Clear All",
	"Clear Comment" : "Clear Comment",
	"Clear Content" : "清除內容",
	"Clear Format" : "Clear Format",
	"Click for live chatting" : "按此打开聊天会议窗口",
	"Click here to report bug" : "按此提交错误报告",
	"Click to Unlock" : "解除编辑锁定",
	"Click to download" : "按此下载",
	"Close" : "关闭",
	"Collaborate" : "Collaborate",
	"Column" : "Column",
	"Column Plot" : "柱形图",
	"Column Width" : "Column Width",
	"Columns" : "列",
	"Columns not Resizable due to Cell/Range Locks" : "由于此操作将会影响到启动了'单元格/范围 锁'的单元格， 无法改变列宽。",
	"Comment" : "Comment",
	"Compete" : "Compete",
	"Contour Plot" : "等高线图",
	"Copy" : "复制",
	"Copy Spreadsheet" : "Copy Spreadsheet",
	"Copy to Clipboard" : "复制到剪贴板",
	"Copy, Ctrl+C" : "复制 Ctrl+C",
	"Create New..." : "Create New...",
	"Creative Commons" : "Creative Commons",
	"Current Date" : "Current Date",
	"Current Date and Time" : "Current Date and Time",
	"Current Sheet" : "Current Sheet",
	"Current Time" : "Current Time",
	"Cut" : "剪切",
	"Cut, Ctrl+X" : "剪切 Ctrl+X",
	"Data" : "数据",
	"Data On Demand" : "Data On Demand",
	"Default" : "默认值",
	"Delete" : "刪除",
	"Delete Column" : "刪除列",
	"Delete Row" : "刪除行",
	"Delete Sheet" : "刪除工作页",
	"Delete Spreadsheet" : "删除电子表格",
	"Deleting Spreadsheets" : "Deleting Spreadsheets",
	"Disable Text Overflow" : "Disable Text Overflow",
	"Do you really want to remove all remote data on this sheet?" : "Do you really want to remove all remote data on this sheet?",
	"Do you still want to proceed?" : "Do you still want to proceed?",
	"Do you want to reload your spreadsheet now?" : "Do you want to reload your spreadsheet now?",
	"Done" : "完成",
	"Down" : "Down",
	"Download / Export" : "下载 / 导出",
	"Drop Bar" : "降柱图",
	"EXPAND is used to expand ranged data, which will fill CONTINUE functions to maximum extend if dimension are not given" : "EXPAND is used to expand ranged data, which will fill CONTINUE functions to maximum extend if dimension are not given",
	"Economy" : "Economy",
	"Edit" : "编辑",
	"Edit Book License" : "Edit Book License",
	"Edit Cell Comment" : "Edit Cell Comment",
	"Edit Cell Hyperlink" : "Edit Cell Hyperlink",
	"Edit Chart" : "编辑图表",
	"Edit Image" : "Edit Image",
	"Edit Note" : "编辑注释",
	"Edit Tags" : "Edit Tags",
	"EditGrid asks" : "EditGrid 询问",
	"EditGrid says" : "EditGrid says",
	"Email" : "电邮",
	"Email Address" : "Email Address",
	"Email Link" : "Email Link",
	"Enable Text Overflow" : "Enable Text Overflow",
	"Enable/Disable Text Overflow" : "启用/禁用 文字溢出",
	"Entire Workbook" : "Entire Workbook",
	"Example" : "Example",
	"Example Usage" : "Example Usage",
	"Exceeded Column Range Limit" : "超出列范围的限制",
	"Exceeded Row Range Limit" : "超出行范围的限制",
	"Existing Cell Content will be removed. Proceed?" : "Existing Cell Content will be removed. Proceed?",
	"Export As" : "导出为",
	"Failed" : "无法执行",
	"Failed to load image from URL: '[_1]'" : "无法载入来自 URL:'&1' 的图像",
	"Failed to open print dialog, pop-up is blocked by your browser." : "打印窗口初始化失败，请确保浏览器的拦截窗口程序允许弹出窗口。",
	"Failed to save the latest change." : "无法保存最后的修改",
	"File" : "文件",
	"Fill" : "Fill",
	"Finance" : "Finance",
	"Find" : "查找",
	"Find <u>N</u>ext" : "下一个 (<u>N</u>)",
	"Find <u>P</u>rev" : "上一个 (<u>P</u>)",
	"Find and Replace" : "Find and Replace",
	"Font Bar" : "Font Bar",
	"Font Color" : "文字颜色",
	"Font Family" : "字型",
	"Font Size" : "字型大小",
	"For complete set of options available, see" : "For complete set of options available, see",
	"Format" : "格式",
	"Format Bar" : "Format Bar",
	"Format Paint" : "Format Paint",
	"Formula Bar" : "Formula Bar",
	"Freeze Panes" : "Freeze Panes",
	"Freeze/Unfreeze Panes" : "冻结/取消冻结 窗格",
	"Functions" : "函数",
	"GNU Free Documentation License" : "GNU Free Documentation License",
	"Get Cell Permalink" : "Get Cell Permalink",
	"Get Object's Permalink" : "此对象的永久链接",
	"Get Range Permalink" : "Get Range Permalink",
	"Go" : "进入",
	"Go To" : "前往",
	"Go to Cell" : "前往单元格",
	"Google Charts" : "Google Charts",
	"HLOOKUP function finds the col in range that has a first row cell similar to value.  If approximate is not true it finds the col with an exact equivalence.  If approximate is true, then the values must be sorted in order of ascending value for correct function; in this case it finds the col with value less than value it returns the value in the col found at a 1-based offset in row rows into the range.  as_index returns the 0-based offset that matched rather than the value." : "HLOOKUP 此函数检验阵列的第一行是否包含特定值。然后此函数返回同一列中由as_index 指定的阵列中的数值。如果約值设定为true，第一行的数值必须由小至大排列，所返回的值将等于少于参数值的上一个列的单元格值。",
	"HTML Table" : "HTML Table",
	"Have 2 or more people working on the same spreadsheet in EditGrid? Each change is reflected in real-time to all editors, meaning that everyone is always working with the latest copy of your spreadsheet." : "Have 2 or more people working on the same spreadsheet in EditGrid? Each change is reflected in real-time to all editors, meaning that everyone is always working with the latest copy of your spreadsheet.",
	"Height" : "高度",
	"Hide Bars" : "Hide Bars",
	"Hide Formula" : "Hide Formula",
	"Hide Live Chat" : "Hide Live Chat",
	"Hide Locked Region" : "Hide Locked Region",
	"Horizontal Drop Bar" : "水平降柱图",
	"Horizontal Min Max Plot" : "水平两极图",
	"Horizontal Min Max Plot (Dotted)" : "水平两极图（标记数据点）",
	"Hyperlink" : "Hyperlink",
	"IF function can be used to evaluate conditionally other expressions.  IF evaluates condition.  If condition returns a non-zero value the result of the IF expression is the if-true expression, otherwise IF evaluates to the value of if-false." : "IF 判定表达式的逻辑值（TRUE 或者 FALSE），根据结果返回对应的值。",
	"If you find this message prompting you consistently and the network limit cannot be raised, " : "If you find this message prompting you consistently and the network limit cannot be raised, ",
	"Image" : "图像",
	"Import" : "导入",
	"In the meantime, we've disabled Live Chat for this session, so only live chat is affected." : "In the meantime, we've disabled Live Chat for this session, so only live chat is affected.",
	"Initialising" : "初始化",
	"Initialising live chat ..." : "Initialising live chat ...",
	"Insert" : "插入",
	"Insert Chart" : "插入图表",
	"Insert Column" : "插入列",
	"Insert Formula" : "插入函数",
	"Insert Mashup" : "Insert Mashup",
	"Insert Row" : "插入行",
	"Insert Sheet" : "插入工作页",
	"Insert Sheet After" : "在此页后插入",
	"Insert Sheet Before" : "在此页前插入",
	"Internal Error: [_1]" : "Internal Error: &1",
	"Internal Link" : "Internal Link",
	"Interpolate between multi-dimensional points with Bezier splines." : "根据Bezier splines插值法来连接数据点。",
	"Invalid Cell Location" : "无效的单元格位置",
	"Invalid Sheet Name" : "无效的工作页名称",
	"Invalid boolean expressions in widget template." : "Invalid boolean expressions in widget template.",
	"Invalid request" : "Invalid request",
	"Invalid response code." : "无效的回应代码",
	"Invalid setup. 'gridletBaseUrl' not defined." : "Invalid setup. 'gridletBaseUrl' not defined.",
	"Invalid setup. 'gridletHost' not defined." : "Invalid setup. 'gridletHost' not defined.",
	"Italic, Ctrl+I" : "斜体 Ctrl+I",
	"Justify" : "Justify",
	"LOOKUP function finds the row index of value in vector1 and returns the contents of vector2 at that row index.  Alternatively a single array can be used for vector1.  If the area is longer than it is wide then the sense of the search is rotated." : "LOOKUP 返回一列或一栏或阵列中单元格的內容。 选择性在不同栏与列中返回指定值 (属于相同索引)。至于VLOOKUP 与HLOOKUP，搜寻与结果向量可能位于不同位置，两者不必相邻。",
	"Labels" : "Labels",
	"Less <<" : "精简 <<",
	"Library Categories Editor" : "Library Categories Editor",
	"License" : "版权",
	"Line" : "折线图",
	"Line Plot" : "折线图",
	"Line Plot (Dotted)" : "折线图（标记数据点）",
	"Linearly interpolate between multi-dimensional points, with markers at each point." : "用直线连接数据点并标记各数据点。",
	"Linearly interpolate between multi-dimensional points." : "用直线连接数据点。",
	"Live Chat" : "即时通讯",
	"Live Chat Disabled" : "Live Chat Disabled",
	"Live View" : "即时查看",
	"Live chat is unavailable" : "Live chat is unavailable",
	"Loading" : "载入中",
	"Lock Spreadsheet" : "Lock Spreadsheet",
	"MAX returns the value of the element of the values passed that has the largest value, with negative numbers considered smaller than positive numbers." : "MAX 返回所选列表中的最大值。",
	"MEDIAN returns the median of the given data set." : "MEDIAN 首先对选中的一组数字按大小进行排列，然后返回这组数字的中位数。如果该组有奇数个数值，中位数将是该组数中间的数字，而在包含偶数个数值的组中，中位数将是该组中间两个值的平均值。",
	"MIN returns the value of the element of the values passed that has the smallest value, with negative numbers considered smaller than positive numbers." : "MIN 返回引数清单中的最小值。",
	"Macro" : "Macro",
	"Magnitude" : "Magnitude",
	"Manage Gridlet" : "Manage Gridlet",
	"Manage Gridlets (Prototype)" : "Manage Gridlets (Prototype)",
	"Manage Remote Data" : "管理远程数据",
	"Manage Spreadsheet Redirections" : "Manage Spreadsheet Redirections",
	"Manage..." : "Manage...",
	"Mark Revision" : "记录修订版本",
	"Mashup" : "Mashup",
	"Max" : "Max",
	"Menu" : "Menu",
	"Merge Cells" : "Merge Cells",
	"Min" : "Min",
	"Min Max" : "两极图",
	"Mini-EditGrid" : "Mini-EditGrid",
	"Minor categories stacked as percentages of the minor total, in horizontal bars, grouped by major category." : "用条形图显示数据在相应的比较数据里所占的百分比。",
	"Minor categories stacked as percentages of the minor total, in vertical bars, grouped by major category." : "用柱形图显示数据在相应的比较数据里所占的百分比。",
	"Minor categories stacked in horizontal bars grouped by major category." : "以条形图显示相应数据堆积的结果。",
	"Minor categories stacked in vertical bars grouped by major category." : "以柱形图显示相应数据堆积的结果。",
	"More >>" : "更多 >>",
	"Multi-dimensional points with circle at each point." : "以三个数值为一组，分别表示圆的大小和圆在x轴和y轴的位置",
	"My Data Format" : "我的数据格式",
	"NOEXPAND avoid automatically adding EXPAND for ranged remotedata" : "NOEXPAND avoid automatically adding EXPAND for ranged remotedata",
	"Name" : "用户名",
	"Network Activity" : "网络活动",
	"New" : "新建",
	"New sheet name" : "New sheet name",
	"No Color" : "预设颜色",
	"No New Message" : "沒有新信息",
	"No user is selected. Please select one." : "您並未选择任何用户。",
	"None (All rights reserved)" : "並沒有设定许可证 (保留所有版权)",
	"Number Format" : "数字格式",
	"Number Format, Ctrl+1" : "数字格式 Ctrl+1",
	"Number Formatting" : "数字格式",
	"OK" : "确定",
	"OR implements the logical OR function: the result is TRUE if any of the values evaluated to TRUE." : "OR 如果至少一个元素是 TRUE 则返回 TRUE。 如果所有元素逻辑值均为 FALSE，此函数则返回值为 FALSE。",
	"Object's Permalink" : "对象的永久链接",
	"Ok" : "确定",
	"Open Console" : "Open Console",
	"Open Publication License" : "Open Publication License",
	"Others" : "Others",
	"Others will not be able to view your spreadsheet unless you set it to be readable by the public." : "Others will not be able to view your spreadsheet unless you set it to be readable by the public.",
	"Password-Protected Read and Write" : "公众可读写(需要密码)",
	"Password-Protected Read-only" : "公众只读(需要密码)",
	"Passwords do not match" : "密码不符",
	"Paste" : "粘贴",
	"Paste Comment" : "Paste Comment",
	"Paste Content" : "Paste Content",
	"Paste Format" : "Paste Format",
	"Paste Special" : "Paste Special",
	"Paste from Clipboard" : "从剪贴板粘贴",
	"Paste from clipboard" : "从剪贴板粘贴",
	"Paste, Ctrl+V" : "粘贴 Ctrl+V",
	"Percentage Area Plot" : "面积图 (百分比)",
	"Percentage Bar Plot" : "条形图 (百分比)",
	"Percentage Column Plot" : "柱形图 (百分比)",
	"Percentage Line Plot" : "折线图 (百分比)",
	"Percentage Line Plot (Dotted)" : "折线图 （标记数据点）",
	"Percentage of each contributor displayed in ring for each serie" : "用圆环图显示数据在相应的比较数据里所占的百分比。",
	"Percentage of each contributor displayed in ring for each serie with wedges of the last ring split apart." : "用圆环图显示数据在相应的比较数据里所占的百分比，并分散显示各比较数据。",
	"Percentage of each contributor with wedges split apart." : "用饼图显示数据在相应的比较数据里所占的百分比，并分散显示各比较数据。",
	"Percentage of each contributor." : "用饼显示数据在相应的比较数据里所占的百分比。",
	"Permalinks" : "永久链接",
	"Permission Denied" : "没有权限",
	"Permission update done" : "Permission update done",
	"Pie" : "饼图",
	"Pie Plot" : "饼图",
	"Pie Plot (Splitted)" : "饼图 （分开）",
	"Please describe your problem briefly:" : "Please describe your problem briefly:",
	"Please enter the new name for the sheet '[_1]'" : "请输入工作页 '&1' 的新名称",
	"Please select a single cell to add comment" : "Please select a single cell to add comment",
	"Please select at least one redirection." : "Please select at least one redirection.",
	"Please select at least one spreadsheet." : "请至少选择一张电子表格。",
	"Please specify a password" : "Please specify a password",
	"Please specify organisation name." : "请输入机构用户 ID",
	"Please specify sheet name." : "请输入工作页名。",
	"Please specify source sheet." : "请指定要插入的工作页。",
	"Please specify source spreadsheet." : "请指定要插入的工作页所属的电子表格。",
	"Please specify username." : "请输入用户名。",
	"Please wait" : "请等候",
	"Please wait while reconnecting..." : "重新连接中，请稍后。",
	"Polar" : "极坐标图",
	"Polar Plot" : "极坐标图",
	"Post to Blog / Webpage" : "贴到日志",
	"Premium" : "Premium",
	"Print" : "打印",
	"Print options" : "Print options",
	"Private" : "不公开",
	"Properties" : "属性",
	"Protected Read and Write" : "可读写(需要密码)",
	"Protected Read-only" : "只读(密码保护)",
	"Public Domain" : "Public Domain",
	"Public Read and Password-Protected Write" : "公众只读，可读写(需要密码）",
	"Public Read and Write" : "公众可读写",
	"Public Read-only" : "公众只读",
	"Public Read/Write" : "Public Read/Write",
	"Publish" : "出版",
	"Publish cell/region as an HTML Table widget" : "Publish cell/region as an HTML Table widget",
	"Publish spreadsheet as a Calculator widget" : "Publish spreadsheet as a Calculator widget",
	"Publish spreadsheet as a Mini-EditGrid widget" : "Publish spreadsheet as a Mini-EditGrid widget",
	"Publish spreadsheet as an HTML Table widget" : "Publish spreadsheet as an HTML Table widget",
	"Purging Deleted Spreadsheets..." : "永久删除己刪除的电子表格...",
	"Quality Feedback Submission" : "Quality Feedback Submission",
	"Quality feedback ticket ID" : "Quality feedback ticket ID",
	"Quick Auto-Filter View" : "Quick Auto-Filter View",
	"Quick Sort View" : "Quick Sort View",
	"ROUND function rounds a given number." : "ROUND 返回一个舍入为一定小数点位数的数字。",
	"Radar" : "雷达图",
	"Radar Area Plot" : "雷达图（填充）",
	"Radar Plot" : "雷达图",
	"Radar Plot (Dotted)" : "雷达图 （标记数据点）",
	"Read" : "可读取",
	"Read and Protected Write" : "公众只读，可读写(需要密码）",
	"Real-time collaboration is our most popular feature." : "Real-time collaboration is our most popular feature.",
	"Recalculate" : "重新计算",
	"Redo" : "恢复输入",
	"Redo, Ctrl+Y" : "恢复输入 Ctrl+Y",
	"Reload" : "重新载入",
	"Remote Data" : "远程数据",
	"Remove Shared Spreadsheet" : "Remove Shared Spreadsheet",
	"Rename Sheet" : "重命名工作页",
	"Rename Spreadsheet" : "Rename Spreadsheet",
	"Renders a chart image in the cell according to the parameters, mashup Compete.com" : "Renders a chart image in the cell according to the parameters, mashup Compete.com",
	"Renders a chart image in the cell according to the parameters, mashup Google Chart API" : "Renders a chart image in the cell according to the parameters, mashup Google Chart API",
	"Renders a chart image in the cell according to the parameters, mashup Reuters.com" : "Renders a chart image in the cell according to the parameters, mashup Reuters.com",
	"Renders a chart image in the cell according to the parameters, mashup Yahoo! Finance" : "Renders a chart image in the cell according to the parameters, mashup Yahoo! Finance",
	"Renders a chart image in the cell according to the paramters, mashup Alexa.com" : "Renders a chart image in the cell according to the paramters, mashup Alexa.com",
	"Replace" : "Replace",
	"Report and Reload" : "Report and Reload",
	"Request aborted" : "Request aborted",
	"Requested action" : "Requested action",
	"Restoring Deleted Spreadsheets..." : "正在还原已刪除的电子表格...",
	"Retry" : "重试",
	"Retry All Remote Data with Error" : "Retry All Remote Data with Error",
	"Reupload Spreadsheet" : "Reupload Spreadsheet",
	"Reuters" : "Reuters",
	"Revisions" : "Revisions",
	"Right" : "Right",
	"Ring" : "圆环图",
	"Ring Plot" : "圆环图",
	"Ring Plot (Splitted)" : "圆环图 （分开）",
	"Row" : "Row",
	"Row Height" : "Row Height",
	"Rows" : "行",
	"Rows not Resizable due to Cell/Range Locks" : "由于此操作将会影响到启动了'单元格/范围 锁'的单元格， 无法改变行高。",
	"SQRT function returns the square root of x." : "SQRT 返回一个数字的正平方根。",
	"STDEV returns the sample standard deviation of the given sample." : "STDEV 根据范例估计标準偏差。",
	"SUBSTITUTE replaces old with new in text.  Substitutions are only applied to instance num of old in text, otherwise every one is changed." : "SUBSTITUTE 用新的文字取代原文。",
	"SUM computes the sum of all the values and cells referenced in the argument list." : "SUM 将选择范围中单元格的所有数字相加。",
	"SUMIF function sums the values in the given range that meet the given criteria.  If actual_range is given, SUMIF sums the values in the actual_range whose corresponding components in range meet the given criteria." : "SUMIF 相加满足给定条件的单元格。 当您搜寻特定值时，此函数用于浏览区域。",
	"Sandbox" : "Sandbox",
	"Save" : "保存",
	"Save As" : "另存为",
	"Saving" : "保存中",
	"Script error processing response (revision: ${grid.revision}, message: ${error.message}, line: ${error.lineNumber})" : "Script error processing response (revision: , message: , line: )",
	"Select" : "Select",
	"Select a format to download" : "选择下载格式",
	"Select background" : "选择背景颜色",
	"Select font color" : "选择文字颜色",
	"Selection" : "Selection",
	"Send" : "发送",
	"Setting up" : "建立中",
	"Share" : "共享",
	"Share to Emails" : "Share to Emails",
	"Share to Public" : "Share to Public",
	"Share to Users" : "Share to Users",
	"Share to the Public" : "Share to the Public",
	"Share with others" : "Share with others",
	"Sheet '[_1]' not found" : "找不到工作页: '&1'",
	"Sheet After" : "工作页后",
	"Sheet Before" : "工作页前",
	"Sheet Properties" : "工作页属性",
	"Show Formula" : "Show Formula",
	"Show Live Chat" : "Show Live Chat",
	"Show Live Chat Window" : "显示聊天对话框",
	"Show Locked Region" : "Show Locked Region",
	"Show/Hide Formula" : "显示/隐藏 公式",
	"Show/Hide Locked Regions" : "显示/隐藏 单元格/范围 锁",
	"Size must be a number" : "Size must be a number",
	"Some changes are not yet saved." : "Some changes are not yet saved.",
	"Some regions of the sheet is being locked by other users" : "Some regions of the sheet is being locked by other users",
	"Sorry! The browser you are now using is not fully supported in this release. You may have problem working with a spreadsheet.<br/>[_1]Please consult here for a list of all supported browsers[_2]." : "Sorry! The browser you are now using is not fully supported in this release. You may have problem working with a spreadsheet.<br/>&1Please consult here for a list of all supported browsers&2.",
	"Sorry! There seems some network errors, please try again later." : "Sorry! There seems some network errors, please try again later.",
	"Sorry, an error has occurred" : "Sorry, an error has occurred",
	"Sorry, this operation is not allowed" : "对不起，不能进行此操作。",
	"Sorry, you have no permission to insert formula." : "Sorry, you have no permission to insert formula.",
	"Sort" : "排序",
	"Sort, Ctrl+Alt+S" : "排序 Ctrl+Alt+S",
	"Sorting is disabled as the currently selected region contains remote data." : "不能在设定的远程数据范围进行排序。",
	"Special" : "Special",
	"Sports" : "Sports",
	"Spreadsheet Copied" : "Spreadsheet Copied",
	"Spreadsheet Ownership Transferred" : "Spreadsheet Ownership Transferred",
	"Spreadsheet Uploaded" : "Spreadsheet Uploaded",
	"Spreadsheet changes are always automatically saved" : "Spreadsheet changes are always automatically saved",
	"Stacked Area Plot" : "面积图 （堆积）",
	"Stacked Bar Plot" : "条形图 （堆积）",
	"Stacked Column Plot" : "柱形图 （堆积）",
	"Stacked Line Plot" : "折线图 （堆积）",
	"Stacked Line Plot (Dotted)" : "折线图 (堆积，标记数据点)",
	"Status" : "状态",
	"Strike, Ctrl+5" : "删线, Ctrl+5",
	"StrikeIron" : "StrikeIron",
	"Subject" : "Subject",
	"Sum Selected Cells" : "求选取单元格的数值总和",
	"Summary" : "总结",
	"Surface" : "表面图",
	"Synopsis" : "Synopsis",
	"Target Range" : "Target Range",
	"Target region contains merged cells and cannot be splitted." : "Target region contains merged cells and cannot be splitted.",
	"Target region contains range lock and cannot be splitted" : "Target region contains range lock and cannot be splitted",
	"Template" : "模板",
	"Template Library" : "Template Library",
	"Template Library Browser" : "Template Library Browser",
	"Text Overflow" : "Text Overflow",
	"Text retrieved from" : "Text retrieved from",
	"The cells you are pasting data into already has data.\nDo you want to overwrite the existing data?\n\nYou can disable this warning under 'Preference > Parameters'" : "您要粘贴到的单元格里面已存在数据。\n您确定要覆盖已存在的数据吗？\n\n您可以到'喜好设定〉参数配置”取消次提示。",
	"There is no need to save changes manually" : "There is no need to save changes manually",
	"These locks will be released as well" : "These locks will be released as well",
	"This operation is unrecoverable" : "This operation is unrecoverable",
	"This spreadsheet is password protected. Click 'unlock', and then provide a valid password to unlock." : "This spreadsheet is password protected. Click 'unlock', and then provide a valid password to unlock.",
	"Timeout while connecting to the EditGrid server. The server may be too busy." : "EditGrid服务器繁忙，连接超时。",
	"To ensure that everything is working correctly, click OK to reload your spreadsheet." : "To ensure that everything is working correctly, click OK to reload your spreadsheet.",
	"Tool Bar" : "Tool Bar",
	"Total [_1] occurrences" : "Total &1 occurrences",
	"Transfer Spreadsheet Ownership" : "Transfer Spreadsheet Ownership",
	"Transferring" : "传输中",
	"Transferring ([_1]kB)" : "传输中 (&1kB)",
	"Unable to connect to the EditGrid server. The network connection may have some problem." : "无法连接到EditGrid服务器。可能是网络出现问题。",
	"Unable to connect to the EditGrid server. The server may be temporarily down." : "无法连接到EditGrid服务器。服务器可能出现问题。",
	"Underline, Ctrl+U" : "下划线 Ctrl+U",
	"Undo" : "撤销",
	"Undo, Ctrl+Z" : "撤销 Ctrl+Z",
	"Unfreeze Panes" : "Unfreeze Panes",
	"Unlock Spreadsheet" : "Unlock Spreadsheet",
	"Unmatched if-then-else statements in widget template" : "Unmatched if-then-else statements in widget template",
	"Update All Linked Sheets" : "更新所有连接工作页",
	"Update Linked Sheet" : "更新连接工作页",
	"Update This Linked Sheet" : "更新此连接工作页",
	"Upload Spreadsheet" : "上传电子表格",
	"Upload new version" : "上传新版本",
	"VAR calculates sample variance of the given sample.  To get the true variance of a complete population use VARP." : "VAR 根据范例估计方差。VARP 根据全部基数计算方差。",
	"VARP calculates the variance of an entire population.  VARP is also known as the N-variance." : "VARP 根据全部基数计算方差。",
	"VLOOKUP function finds the row in range that has a first column similar to value.  If approximate is not true it finds the row with an exact equivalence.  If approximate is true, then the values must be sorted in order of ascending value for correct function; in this case it finds the row with value less than value.  It returns the value in the row found at a 1-based offset in column columns into the range.  as_index returns the 0-based offset that matched rather than the value." : "VLOOKUP 此函数检验阵列的第一列是否包含特定值。然后此函数返回同一行中由as_index 指定的阵列中的数值。如果約值设定为true，第一行的数值必须由小至大排列，所返回的值将等于少于参数值的上一个列的单元格值。",
	"Values" : "Values",
	"Vertical Drop Bar" : "垂直降柱图",
	"Vertical Min Max Plot" : "垂直两极图",
	"Vertical Min Max Plot (Dotted)" : "垂直两极图 （标记数据点）",
	"Vertically Align Bottom" : "Vertically Align Bottom",
	"Vertically Align Center" : "Vertically Align Center",
	"Vertically Align Top" : "Vertically Align Top",
	"View" : "查看",
	"View Revisions" : "查看修订版本",
	"Visit the permalink" : "Visit the permalink",
	"We will figure out how to resolve the problem. You may wish to [_1]reload this page[_2] to continue your work." : "We will figure out how to resolve the problem. You may wish to &1reload this page&2 to continue your work.",
	"Web" : "Web",
	"Web Address" : "Web Address",
	"Web Analytics" : "Web Analytics",
	"Web Link" : "Web Link",
	"Widgets" : "Widgets",
	"Width" : "寛度",
	"Word Wrap" : "自动换行",
	"Write" : "可编辑",
	"XY Curve Plot" : "XY 弧线图",
	"XY Line Plot" : "XY 折线图",
	"XY Line Plot (Dotted)" : "XY 折线图 （标记数据点）",
	"XY Plot (Dots Only)" : "XY 散点图",
	"XY Scatter" : "XY 散点图",
	"Xignite" : "Xignite",
	"Yahoo! Finance" : "Yahoo! Finance",
	"You are advised to read the license text:" : "You are advised to read the license text:",
	"You are going to copy a large range and this may consume up to a few minutes. Are you sure you want to do so?" : "您正准备复制大范围的单元格，可能需要数分钟进行。您仍想继续吗？",
	"You are going to paste a large amount of text and this may consume up to a few minutes. Are you sure you want to do so?" : "您正准备粘贴大范围的单元格，可能需要数分钟进行。您仍想继续吗？",
	"You are not able to lock the currently selected region as parts of it have already been locked by another user." : "无法锁定所选范围，此范围已被其他用户锁定。",
	"You are not able to modify the currently selected region as it has been locked by another user." : "您无法修改所选范围，此范围已被其他用户锁定。",
	"You are not able to modify this cell as it has been locked by another user." : "无法修改所选单元格，此单元格已被其他用户锁定。",
	"You have now associated the following license terms to your spreadsheet:" : "You have now associated the following license terms to your spreadsheet:",
	"You haven't assigned a name to this sheet." : "You haven't assigned a name to this sheet.",
	"You'll lose these changes if you navigate away before saving is completed." : "You'll lose these changes if you navigate away before saving is completed.",
	"Your network settings seem not supporting 3 concurrent connections, please contact your network administrator. " : "Your network settings seem not supporting 3 concurrent connections, please contact your network administrator. ",
	"Your spreadsheet is not public readable." : "Your spreadsheet is not public readable.",
	"a range, eg. B11:D15" : "a range, eg. B11:D15",
	"alexa" : "alexa",
	"allow public visitors to view" : "允许公众查看",
	"allow public visitors to view and edit" : "允许公众查看和修改",
	"allow public visitors to view, and allow editing when a valid password is given" : "准许公众查看，但需要通过密码验证才能编辑",
	"allow public visitors with a valid password to view" : "可供公众查看,但需要密码验证",
	"allow public visitors with a valid password to view and edit" : "可供公众查看和修改,但需要密码验证",
	"cia_factbook" : "cia_factbook",
	"close" : "close",
	"compete" : "compete",
	"crunchbase" : "crunchbase",
	'duration of data, eg. 7, 180, "1year", "3year"' : "duration of data, eg. 7, 180, \"1year\", \"3year\"",
	"height of image" : "height of image",
	"ipdata" : "ipdata",
	"list of website names, separated by [_1]" : "list of website names, separated by &1",
	"login" : "login",
	"no public visitor can view or edit" : "不允许公众查看或编辑",
	"option=value pairs separated by [_1]" : "option=value pairs separated by &1",
	"pagerank" : "pagerank",
	"pixels" : "pixels",
	"processing..." : "processing...",
	"reuters_delayquote" : "reuters_delayquote",
	"reuters_financials" : "reuters_financials",
	"reuters_fundamentals" : "reuters_fundamentals",
	"reuters_historical" : "reuters_historical",
	"reuters_lookup" : "reuters_lookup",
	"says" : "说",
	"shows chart in logarithmic scale; possible values: 0, 1" : "shows chart in logarithmic scale; possible values: 0, 1",
	"stock ticker, i.e. GOOG" : "stock ticker, i.e. GOOG",
	"stock ticker, i.e. YHOO" : "stock ticker, i.e. YHOO",
	"strikeiron_census" : "strikeiron_census",
	"strikeiron_mlb" : "strikeiron_mlb",
	"strikeiron_mlb_players" : "strikeiron_mlb_players",
	"strikeiron_mlb_teams" : "strikeiron_mlb_teams",
	"strikeiron_zacks" : "strikeiron_zacks",
	"sum" : "总和",
	"time range to plot; possible values: 1d, 5d, 3m, 6m, 1y, 2y, 5y, max" : "time range to plot; possible values: 1d, 5d, 3m, 6m, 1y, 2y, 5y, max",
	"time range to plot; possible values: 7d, 1m, 3m, 6m, 1y, 3y, 5y, max" : "time range to plot; possible values: 7d, 1m, 3m, 6m, 1y, 3y, 5y, max",
	"to join chat room." : "to join chat room.",
	"to join." : "to join.",
	"we suggest you to disable Live Chat at 'Preferences > Spreadsheet Interaction'." : "we suggest you to disable Live Chat at 'Preferences > Spreadsheet Interaction'.",
	"web" : "web",
	"web_csv" : "web_csv",
	"web_feed" : "web_feed",
	"web_list" : "web_list",
	"web_regex" : "web_regex",
	"web_table" : "web_table",
	"web_tsv" : "web_tsv",
	"web_xpath" : "web_xpath",
	"website name" : "website name",
	"whois" : "whois",
	"width of image" : "width of image",
	"xignite_commodity" : "xignite_commodity",
	"xignite_dividends" : "xignite_dividends",
	"xignite_estimates" : "xignite_estimates",
	"xignite_financials" : "xignite_financials",
	"xignite_fund" : "xignite_fund",
	"xignite_futures" : "xignite_futures",
	"xignite_fx" : "xignite_fx",
	"xignite_logo" : "xignite_logo",
	"xignite_market_news" : "xignite_market_news",
	"xignite_markets" : "xignite_markets",
	"xignite_news" : "xignite_news",
	"xignite_splits" : "xignite_splits",
	"xignite_stock" : "xignite_stock",
	"ycurrency" : "ycurrency",
	"yhistorical" : "yhistorical",
	"ystock" : "ystock",
	"ystocknews" : "ystocknews",
	"" : ""
}

function _localeLookup(s) { return _locale[s] }
